#include <pmman.h>
#include <debug_io.h>

static u64 map[64] = {0};

void pmman_initialize(memmap_t* memmap, u32 memmap_count) {
	dbg_puts("\nInitializing physical memory manager\n");

	// Print memory map generated by BIOS 0x15/0xE820
	for (int i = 0; i < memmap_count; ++i) {
		u64 base = memmap[i].base, len = memmap[i].len;
		dbg_printf(DBG_GRY"0x%hq -> 0x%hq : %uq Bytes, Type: %s\n"DBG_RST,
				base, base + len, len, memmap_type_str(memmap[i].type));
	}
}

